### ISSUE TITLE
Streaming Transactions

### ISSUE THREAD

**Issue by maja42** [arangodb/go-driver#459]
It seems that transactions with BeginTransaction(), CommitTransaction() and AbortTransaction() should be supported.
The database knows them, and these methods exist in the driver's go API.

But there is no documentation, or examples whatsoever. There was already an issue requesting documentation (before the streaming-API was added), but it was closed: https://github.com/arangodb/go-driver/issues/84

After some digging and trial-and-error, I think that the current state of the go API is broken and it's not possible to use transactions.
BeginTransaction returns a transaction ID, but there is no other API where it could be used.

I would expect it in the `Collection()` method(s), or in the methods provided by a collection (eg. `ReadDocument`, `CreateDocument`, `UpdateDocument`, ...). Alternatively, the context could hold a transaction ID, but it doesn't either.

What's the status of transactions? Am I missing something? (I'm using v1.4.0)

**Comment by jwierzbo** [comment]
@maja42 here you can see the exampled requests:
https://github.com/arangodb/go-driver/blob/f21fd265f46e2fcc5d57d62758ea5983a942df22/test/database_transaction_test.go#L96-L157

Basically you need to use context with transactionId (check this method: `driver.WithTransactionID`)

Documentation is available here:
https://www.arangodb.com/docs/3.10/http/transaction-stream-transaction.html

**Comment by maja42** [comment]
I just tested it, and it works. 
Though, based on the documentation, I'm not sure if I understood the "write" lock correctly. Does

>  if two concurrent transactions attempt to modify the same document or index entry

mean that a transaction locks every individual document (that was created or written to), and, if another operation tries to modify those documents before the original transaction was comitted, it will fail?

In any way, I think Arango would benefit greatly if the [inline GoDoc documentation](https://pkg.go.dev/github.com/arangodb/go-driver) would be reworked, so that it's sufficient to read the GoDoc instead of trying to find the correct google search terms.
It would already help if the individual methods or config-objects would contain links to the relevant sections in the official documentation.

**Comment by jwierzbo** [comment]
Every transaction in ArangoDB will lock the documents it inserts, updates, replaces or removes (plus the corresponding index entries).
The locks are held until the transaction commits or aborts.
Transactions that modify different documents can run fully concurrently.
Transactions that modify the same documents cannot run concurrently, because then one transaction may overwrite the modifications of another. That would cause lost updates or any other sort of anomalies and inconsistencies.
What happens instead is that if a transaction tries to lock a document/index entry that another transaction has already locked, it will return a "write-write conflict" error. The client application can then handle this error and either propagate it or retry the transaction.
It is also possible to avoid write-write conflicts altogether by marking write operations as "exclusive". The big caveat here is that this will limit concurrency for write operations to the underlying collection to 1.

https://www.arangodb.com/docs/stable/transactions-locking-and-isolation.html#locking

We are working on go-driver V2 - we will take into account your suggestion about doc there.
