### ISSUE TITLE
Implement transactions

### ISSUE THREAD

**Issue by phifty** [arangodb/go-driver#56]
It seems like they are missing.

Thanks in advance,
Phifty

**Comment by ewoutp** [comment]
@phifty Currently the go driver does not support the transaction API of ArangoDB because that API requires the use of javascript. 
For the go driver that would means that you as a client programmer would have to write that actions that you want to transaction to wrap in javascript. Then wrap that in a string and pass that to the go driver. 
We want to avoid that.

Now we're working a more advanced transaction API to ArangoDB which will be supported with "normal" go code. 
The bad news is that this new transaction API will not be available for the upcoming version. An exact version or date is not yet known.

Regards
Ewout

**Comment by phifty** [comment]
@ewoutp Thanks for the quick reply.
I'm aware that Arango transaction are written in Javascript. But I don't think the Go client would need to interpret it. I would like to pass just a Javascript-String to the server. Just like the AQL queries are passed there. I see the transactions just written in a different query language.
The implementation should be quite simple. If I find the time, I could start a pull request in the next days.

**Comment by ewoutp** [comment]
@phifty Yes, you can surely write it yourself using the `Connection` class that you can get from your `Client`. 
Honestly I doubt this will be merged into the main branch, but having a solution for it would certainly help multiple people.

**Comment by phifty** [comment]
I implemented a first draft at PR #57
