### ISSUE TITLE
Initialise Database struct without sending requests to the cluster

### ISSUE THREAD

**Issue by wopol** [arangodb/go-driver#570]
Having initialized `Client`, we have two options to get the `Database` struct. We can call `Database` or `CreateDatabase` functions, but both send requests to an arangoDB cluster.

I want to skip this request because access to the DB may be temporarily not available, and I want to allow my application to start and later handle request failure in the app. Being unable to initialize `Database` struct at the startup forces me to use mutex later when I want to perform specific operations and need to check whether `Database` struct has been initialized.

It looks like we could easily initialize `Database` by providing a name because the client already has a connection pool. What do you think about this solution? Could we allow to initialize `Database` struct just by providing a database name?

**Comment by jwierzbo** [comment]
Could you consider using raw query or wait till ArangoDB is ready and then open the connection to the Database?

We are not planning to change the current logic...

**Comment by wpvosbor** [comment]
What do you mean by raw query? My app can work without ArangoDB, therefore I would like to proceed even when ArangoDB is unavailable. I could wait in the background, but then I need to implement complex logic with mutex because whenever someone wants to use functionality that needs ArangoDB under the hood, then first of all, I need to check whether `driver.Database` struct is created.

There is no issue when the connection is lost later because then the `driver.Database` struct is already initialized, and the connection pool under the hood takes care of it. Everything what I need to do is handle connection error.

Ideally would be able to initialize `driver.Database` struct even when a database is not available at that moment. From what I see in order to do that only databaseName and connection poll is needed.

**Comment by wopol** [comment]
What do you mean by raw query? My app can work without ArangoDB, therefore I would like to proceed even when ArangoDB is unavailable. I could wait in the background, but then I need to implement complex logic with mutex because whenever someone wants to use functionality that needs ArangoDB under the hood, then first of all, I need to check whether `driver.Database` struct is created.

There is no issue when the connection is lost later because then the `driver.Database` struct is already initialized, and the connection pool under the hood takes care of it. Everything what I need to do is handle connection error.

Ideally would be able to initialize `driver.Database` struct even when a database is not available at that moment. From what I see in order to do that only databaseName and connection poll is needed.

**Comment by jwierzbo** [comment]
Here is the example how to use raw query:
https://github.com/arangodb/go-driver/blob/10aa09b26d5f760fc002727377fc642338a0f641/v2/tests/call_test.go#L61-L69

**Comment by wopol** [comment]
It will not work for me. If I understand correctly, I will need to rewrite every single method into raw query.

**Comment by jwierzbo** [comment]
We will add new method  to initialise Database object soon then

**Comment by wopol** [comment]
@jwierzbo, how is it going? When could we expect to have it?

**Comment by jwierzbo** [comment]
It is in master already
