### ISSUE TITLE
Need sample program that uses velocypack 

### ISSUE THREAD

**Issue by RaghavendraGopinath** [arangodb/go-driver#618]
We have a requirement where we have to replace json with protobuf for performance reasons. Since protobuf is not supported, we would like to try velocypack and check if it is more performant. By performance, I am referring to our application performance and not ArangoDB performance.

Can you please provide us a sample / test program that demonstrates the use of velocypack.Marshal() and velocypack.Unmarshal()?

**Comment by kvahed** [comment]
Hi @RaghavendraGopinath 
I am not sure if I fully understand your request. protobuf being of course an interchange standard / format I assume that you must be refering to velocystream, VST for short? Please correct me if I misunderstood. Velocypack is our internal serialisable JSON library in C++. 
Please do not use VST. The reason is that the gravity team is moving to version 3.12 of ArangoDB where the support for VST is dropped for http/http2.
Thus, provided I understood your request right, I would close this ticket as deprecated. I am reaching out directly to discuss your options.
With my highest regards
- K
